networks:
  vpn-bot:
    external: true

services:
  main-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: main-service:latest
    networks:
      - vpn-bot

  migrations:
    image: main-service:latest
    command:  [ "alembic", "upgrade", "head"]
    env_file:
      - env/.env
    depends_on:
      - main-service
    networks:
      - vpn-bot

  web_application:
    image: main-service:latest
    command: ["python", "-m", "src"]
    ports:
      - "8000:8000"
    env_file:
      - env/.env
    depends_on:
      - migrations
    networks:
      - vpn-bot
