networks:
  vpn-bot:
    external: true

services:
  main-service:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: main-service:dev

  migrations:
    image: main-service:dev
    command: ["alembic", "upgrade", "head"]
    env_file:
      - env/.env
    depends_on:
      - main-service
    networks:
      - vpn-bot

  web_application:
    image: main-service:dev
    ports:
      - "8000:8000"
    env_file:
      - env/.env
    depends_on:
      - migrations
    networks:
      - vpn-bot
    volumes:
      - ./src:/app/src
    command: ["watchmedo", "auto-restart", "--directory=/app", "--pattern=*.py", "--recursive", "--", "python", "-m", "src"]
