networks:
  vpn-network:
    external: True

services:
  main-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - vpn-network
    image: main-service

  migrations:
    image: main-service
    command:  [ "alembic", "upgrade", "head"]
    env_file:
      - env/.env
    restart: ""
    networks:
      - vpn-network
    depends_on:
      - main-service

  web_application:
    image: main-service
    command: ["python", "-m", "src"]
    ports:
      - "8000:8000"
    env_file:
      - env/.env
    networks:
      - vpn-network
    depends_on:
      - migrations
